import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from '@/components/ui/sonner'
import Loading from '@/components/ui/loading'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'active syslog',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Loading />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
